### ISSUE TITLE
[Feature] Splitter en microservices

### ISSUE THREAD

**Issue by yatho** [ptitbob/quarkus-demo-source#13]
Je vois deux micro services :

1. City
2. Person

**Comment by ptitbob** [comment]
oui, c'est en grande partie mon test
je vais y reflechir :)

**Comment by yatho** [comment]
Il n'y a pas de jointure entre les entités personnes et villes ? Du coup il y a même pas de corrélation entre les deux. Le mieux serait deux webservices en cascade pour montrer la facilité de mise en oeuvre.

**Comment by yatho** [comment]
Mais le temps est compté on peut dire que ce serait un bonus

**Comment by ptitbob** [comment]
grmmlbl tu m'oblige ce que je savais devoir faire :D

**Comment by yatho** [comment]
Fait les slides en premier :D

**Comment by yatho** [comment]
Je pense que je peux clore l'issue :D
